"""empty message

Revision ID: 2b2e1defebfd
Revises: baeb85c1f0e1
Create Date: 2023-11-22 09:25:37.583051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2e1defebfd'
down_revision = 'baeb85c1f0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skin_cancer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skin_cancer_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cancerList', sa.String(length=20), nullable=False),
    sa.Column('cancerDesc', sa.String(length=100), nullable=False),
    sa.Column('pibuMap', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=11), nullable=False),
    sa.Column('password', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('agree', sa.Integer(), nullable=False),
    sa.Column('skinImage', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('answer')
    op.drop_table('question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('social_login')
    op.drop_table('skin_cancer_result')
    op.drop_table('skin_cancer')
    # ### end Alembic commands ###
