"""empty message

Revision ID: d6cd16871081
Revises: 6b86be4e71f7
Create Date: 2023-12-26 09:15:02.716417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6cd16871081'
down_revision = '6b86be4e71f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_social_login')
    with op.batch_alter_table('social_login', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agree_personal', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('agree_location', sa.Integer(), nullable=True))
        batch_op.drop_column('agree')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_login', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agree', sa.INTEGER(), nullable=False))
        batch_op.drop_column('agree_location')
        batch_op.drop_column('agree_personal')

    op.create_table('_alembic_tmp_social_login',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=11), nullable=False),
    sa.Column('password', sa.VARCHAR(length=11), nullable=False),
    sa.Column('email', sa.VARCHAR(length=30), nullable=False),
    sa.Column('gender', sa.INTEGER(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('skinImage', sa.VARCHAR(length=50), nullable=True),
    sa.Column('agree_personal', sa.INTEGER(), nullable=False),
    sa.Column('agree_location', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
