"""empty message

Revision ID: 528cea7f0f37
Revises: 2b2e1defebfd
Create Date: 2023-11-22 11:32:57.699641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528cea7f0f37'
down_revision = '2b2e1defebfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skin_cancer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_login_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('skin_cancer_result_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'skin_cancer_result', ['skin_cancer_result_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'social_login', ['social_login_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skin_cancer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('skin_cancer_result_id')
        batch_op.drop_column('social_login_id')

    # ### end Alembic commands ###
